CREATE TABLE Sessoes
(
    Id UNIQUEIDENTIFIER DEFAULT(NEWID())  PRIMARY KEY NOT NULL,
    Titulo NVARCHAR(255) NOT NULL,
    Apresentador NVARCHAR(100) NOT NULL,
    Host NVARCHAR(100) NOT NULL,
    DataSessao DATETIME NOT NULL
)